Adapt class Person to Student to fit with TAchy's model design
AY2425S1-CS2103-F11-1/tp pull request #51
Opened 2024-10-04 15:23 UTC by jian7490

2024-10-04 17:20 UTC, lm-44 requested changes
I've tried my very best to go through the code HAHAHA. My eyes hurt. I think majority of it is fine, just some nits. Other than that LGTM!

2024-10-04 17:20 UTC, lm-44 commented on src/test/java/seedu/address/testutil/PersonUtil.java
> +import seedu.address.logic.commands.EditCommand;
Maybe import EditCommand.EditStudentDescriptor?

2024-10-04 17:20 UTC, lm-44 commented on src/test/java/seedu/address/testutil/PersonUtil.java
> +    public static String getEditPersonDescriptorDetails(EditCommand.EditStudentDescriptor descriptor) {
With the above import changed, you can remove "EditCommand."

2024-10-07 17:03 UTC, jian7490 commented on src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
>   * Represents an error which occurs during execution of a {@link Command}.
Sure. Good advice to me on improving  the code quality!

2024-10-07 17:03 UTC, jian7490 commented on src/main/java/seedu/address/model/student/Student.java
> -    // Data fields
Solid point. I believe it was removed by accident.

2024-10-08 15:31 UTC, emmannyyy commented on src/test/java/seedu/address/logic/parser/ParserUtilTest.java
> -
If we do intend on keeping address, then we should recover these tests. Let's discuss with the team if keeping address is the right way to go

2024-10-08 15:31 UTC, emmannyyy commented on src/test/java/seedu/address/model/person/AddressTest.java
Same, may want to keep this test

2024-10-08 15:31 UTC, emmannyyy commented on src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
> -        String expectedMessage = String.format(MISSING_FIELD_MESSAGE_FORMAT, Address.class.getSimpleName());
same here, may have to recover this

2024-10-10 11:50 UTC, merged